### ISSUE TITLE
Paper 1.16.1 No backups being made

### ISSUE THREAD

**Issue by wakeboy9** [enayet123/BackupOnEventPlugin#4] opened 2020-07-28 04:53 UTC
I can trigger the command to backup via console or leaving the server as the last player, but no backup is actually made. The server says there is a zip file made but there is not one. I checked in both the backups folder and the BackupOnEvent plugin folder. 

This is my first time using Paper and mods, but I think I set it up correctly because everything else works as intended and the plugin gives messages to suggest it is working.

**Comment by enayet123** [comment] 2020-07-28 08:58
Hey, I'm struggling to reproduce this issue using BackupOnEvent 1.6.3 with Minecraft 1.16.1 running on MacOS Catalina. Are you looking in the folder called "backup"? This is the current folder all backups go to. If the issue is still present drop me a message using Discord, Enayet#7631

**Comment by wakeboy9** [comment] 2020-07-28 17:19
I did look into a folder called "backups" in the same folder as the server jar. I even tried deleting it and running a new backup and the plugin did recreate it. But no backups still. I am running Windows 10.

![log](https://user-images.githubusercontent.com/55433397/88699078-e1504600-d0d4-11ea-92a3-6769c7105618.png)

**Comment by enayet123** [comment] 2020-07-28 17:41
World was renamed in `server.properties`. Issue resolved by updating `config.yml` for BackupOnEvent. Noted possible confusion caused by `config.yml` being generated with "world" as default with intention to improve in next release

**Closed as completed by enayet123** 2020-07-28 17:41 UTC
Labels: bug
